### ISSUE TITLE
Windows 10 python 3.7

### ISSUE THREAD

**Issue by Pedromacedo41** [pybox2d/pybox2d#113]
When trying installing via pip or by source, get the following error:

```python
Traceback (most recent call last):
  File "setup.py", line 176, in <module>
    setup(**setup_dict)
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\ProgramData\Miniconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\ProgramData\Miniconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\ProgramData\Miniconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Miniconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\ProgramData\Miniconda3\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\ProgramData\Miniconda3\lib\distutils\_msvccompiler.py", line 346, in compile
    self.initialize()
  File "C:\ProgramData\Miniconda3\lib\distutils\_msvccompiler.py", line 239, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
    return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
  File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\msvc.py", line 1623, in return_env
    if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
  File "C:\ProgramData\Miniconda3\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by kne** [comment]
Would you be willing to try conda instead?

`conda install -c conda-forge pybox2d`

**Comment by Pedromacedo41** [comment]
Thanks for your answer

yes, i tried :(

**Comment by kne** [comment]
The new conda-forge builds are from the past week - when did you give it a go?

If you haven't tried it recently, please give the following a go:
```
conda create -c conda-forge -n new_pybox2d python=3.7 pybox2d
conda activate new_pybox2d
```

Can you paste the new output if you run into an issue?

**Comment by Pedromacedo41** [comment]
This worked for me ! Thanks :)
