### ISSUE TITLE
Examples in README not working.

### ISSUE THREAD

**Issue by eabase** [pybox2d/pybox2d#139]
The package is used from other dependencies and it work, but none of the examples as suggested in the readme. 

Apparently the new way to install this is by:
```python
# pip install -U gymnasium[box2d]

# <run app - everything OK> 

# python -m Box2D.examples.web --backend=pygame

C:\xxx\xxx\Scripts\python.exe: Error while finding module specification for 'Box2D.examples.web' (ModuleNotFoundError: No module named 'Box2D.examples')
```

I also tried following the `git clone` method and navigating to examples.
Same issue:

```powershell
cd C:\xxx\gitclones\pybox2d\my_new_examples

# python -m web --backend=pygame
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\xxx\gitclones\pybox2d\my_new_examples\web.py", line 21, in <module>
    from Box2D.examples.framework import (Framework, Keys, main)
ModuleNotFoundError: No module named 'Box2D.examples'

# python.exe -qu -X utf8=1 -c "import Box2D; print('Box2D Version: {}\nGlobals: {}'.format(Box2D.__version__,Box2D.b2Globals.b2_version)); m='\x1b[30;41m OK \x1b[0m'; print(m);"

Box2D Version: 2.3.5
Globals: b2Version(2.3.0)
 OK

```

How to install and use the examples?

Please update your README.

**Comment by kne** [comment]
* New wheels are up on [PyPI](https://pypi.org/project/Box2D/2.3.10/#files) for Python 3.6-3.13 on Linux/macOS/Windows x86-64 and arm64 (install with `pip install Box2D`).
* New [conda packages](https://anaconda.org/conda-forge/pybox2d/files) are up on conda-forge for Python 3.9-3.13 (install with `conda install pybox2d`).

I can't/won't support repackaged versions of pybox2d (the `box2d-py` package utilized by `gymnasium`), so please give one of the above a try.
