### ISSUE TITLE
Error during install:  KeyError: '_Box2D' (Ubuntu Karmic 64bit; setuptools)

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#23]
_From [thehans](https://code.google.com/u/106086923980898291910/) on September 13, 2009 03:22:12_

What steps will reproduce the problem? 1. run easy_install box2d

I get the following output which ends in an error:

Processing Box2D-2.0.2b1-py2.5-linux-i686.egg
Removing
/usr/local/lib/python2.6/dist-packages/Box2D-2.0.2b1-py2.5-linux-i686.egg
Copying Box2D-2.0.2b1-py2.5-linux-i686.egg to
/usr/local/lib/python2.6/dist-packages
Box2D 2.0.2b1 is already the active version in easy-install.pth

Installed
/usr/local/lib/python2.6/dist-packages/Box2D-2.0.2b1-py2.5-linux-i686.egg
Processing dependencies for Box2D==2.0.2b1
Searching for Box2D==2.0.2b1
Reading http://pypi.python.org/simple/Box2D/ Reading http://pybox2d.googlecode.com/ Reading https://code.google.com/p/pybox2d/downloads/list Best match: Box2D 2.0.2b1
Downloading http://pybox2d.googlecode.com/files/Box2D-2.0.2b1.zip Processing Box2D-2.0.2b1.zip
Running Box2D-2.0.2b1/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-ROjLE6/Box2D-2.0.2b1/egg-dist-tmp-5i2MYq
Using setuptools.
Traceback (most recent call last):
  File "/usr/local/bin/easy_install", line 8, in \<module>
    load_entry_point('setuptools==0.6c9', 'console_scripts', 'easy_install')()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 1671, in main
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 1659, in with_ei_usage
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 1675, in \<lambda>
    
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 211, in run
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 427, in easy_install
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 478, in install_item
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 519, in process_distribution
    
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 522, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 758, in best_match
    return self.obtain(req, installer) # try and download/install
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 770, in obtain
    return installer(requirement)
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 446, in easy_install
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 476, in install_item
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 655, in install_eggs
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 930, in build_and_install
    
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py",
line 919, in run_setup
    
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 27, in
run_setup
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 63, in run
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 29, in \<lambda>
  File "setup.py", line 109, in \<module>
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/bdist_egg.py", line
174, in run
  File "build/bdist.linux-i686/egg/setuptools/command/bdist_egg.py", line
161, in call_command
  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/install_lib.py", line
20, in run
  File "/usr/lib/python2.6/distutils/command/install_lib.py", line 113, in
build
    self.run_command('build_ext')
  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/build_ext.py", line
46, in run
  File "/usr/lib/python2.6/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python2.6/distutils/command/build_ext.py", line 449, in
build_extensions
    self.build_extension(ext)
  File "build/bdist.linux-i686/egg/setuptools/command/build_ext.py", line
175, in build_extension
  File "/usr/lib/python2.6/distutils/command/build_ext.py", line 460, in
build_extension
    ext_path = self.get_ext_fullpath(ext.name)
  File "/usr/lib/python2.6/distutils/command/build_ext.py", line 633, in
get_ext_fullpath
    filename = self.get_ext_filename(modpath[-1])
  File "build/bdist.linux-i686/egg/setuptools/command/build_ext.py", line
85, in get_ext_filename
KeyError: '_Box2D'

Running this on Ubuntu Karmic 64bit

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=23_

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on September 13, 2009 19:17:19_

Never saw this one. Don't have a 64-bit platform to test on now; have you gotten any
further? Not sure why setuptools would be failing.

**Summary:** Error during install:  KeyError: '_Box2D' (Ubuntu Karmic 64bit; setuptools)

**Comment by kne** [comment]
_From [thehans](https://code.google.com/u/106086923980898291910/) on September 13, 2009 20:19:29_

I have not gotten any further.  I have no idea how to get around this.  I'm fairly
new to python and pygame and hardly know what I'm doing.

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on January 04, 2010 06:42:27_

This is an issue in older versions of setuptools; I found it here: http://bitbucket.org/tarek/distribute/issue/41/ I'll consider making a patch for setup.py, but for now please update your setuptools
version.

**Labels:** -Priority-Medium Priority-Low

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on January 11, 2010 06:42:44_

Fixed in the 2.1.0 branch. Won't fix it in the old 2.0.2 version.

**Status:** Fixed
