### ISSUE TITLE
Windws 7 Python x64 build fails / distutils

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#26]
_From [mason.green](https://code.google.com/u/113158675721513411716/) on October 31, 2009 00:21:42_

System setup:

Windows 7 x64
Python 2.6.4 x64
MSVC Express '08

$ python setup.py build
Setuptools not found; falling back on distutils.
running build
running build_py
copying .\Box2D.py -> build\lib.win-amd64-2.6\Box2D
copying .\__init__.py -> build\lib.win-amd64-2.6\Box2D
running build_ext
building 'Box2D._Box2D' extension
swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
c:\swig\swig.exe -python -c++ -IBox2D -O -includeall -ignoremissing -w201
-outdi
r . -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
Traceback (most recent call last):
  File "setup.py", line 109, in \<module>
    setup( **setup_dict )
  File "c:\Python26\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\Python26\lib\distutils\dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "c:\Python26\lib\distutils\dist.py", line 995, in run_command
    cmd_obj.run()
  File "c:\Python26\lib\distutils\command\build.py", line 134, in run
    self.run_command(cmd_name)
  File "c:\Python26\lib\distutils\cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "c:\Python26\lib\distutils\dist.py", line 995, in run_command
    cmd_obj.run()
  File "c:\Python26\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "c:\Python26\lib\distutils\command\build_ext.py", line 449, in
build_exte
nsions
    self.build_extension(ext)
  File "c:\Python26\lib\distutils\command\build_ext.py", line 499, in
build_exte
nsion
    depends=ext.depends)
  File "c:\Python26\lib\distutils\msvc9compiler.py", line 448, in compile
    self.initialize()
  File "c:\Python26\lib\distutils\msvc9compiler.py", line 358, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "c:\Python26\lib\distutils\msvc9compiler.py", line 274, in
query_vcvarsal
l
    raise ValueError(str(list(result.keys())))
ValueError: [u'path']

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=26_

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on January 11, 2010 06:42:01_

I realize this is a very old issue, but if you're still around -- try installing
setuptools and see what happens then. On x64 you'll also need the SVN version instead
of the 2.0.2b1 source zip.

**Summary:** Windws 7 Python x64 build fails / distutils

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on August 31, 2013 07:35:53_

setuptools/distribute should just be a basic requirement now.

**Status:** WontFix
