### ISSUE TITLE
pybox2d and py2exe

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#28]
_From [psnim2000](https://code.google.com/u/108640596060608327473/) on January 19, 2010 17:54:23_

What steps will reproduce the problem? 1. Attempt to build an executable with py2exe, have the program use 
pybox2d. What is the expected output? What do you see instead? Error-
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "util.pyo", line 1, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "Box2D__init__.pyo", line 23, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "Box2D\Box2D.pyo", line 44, in <module>
  File "Box2D\Box2D.pyo", line 39, in swig_import_helper
ImportError: No module named _Box2D What version of the product are you using? On what operating system? 2.0.21b, with Python 2.6 (x86)

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=28_

**Comment by kne** [comment]
_From [benjamin.debski](https://code.google.com/u/benjamin.debski@gmail.com/) on January 20, 2010 15:59:03_

I can confirm this and have found two temporary solutions:
1. Copy the Box2d folder to the working directory
2. Edit Box2D.py commenting out the whole if version_info >= (2,6,0): else block and
replace with just import _Box2D

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on January 23, 2010 20:04:07_

Thanks for the tips, Benjamin. I'm not entirely sure of the reason behind this. I'd
imagine py2exe has trouble with every SWIG-based project if it can't handle pybox2d.
I'll get this on the Box2D if it ever comes back up, or I'll eventually have to make
my own page here.

**Summary:** pybox2d and py2exe  
  **Status:** Accepted  
  **Labels:** -Priority-Medium Priority-Low

**Comment by kne** [comment]
10+ year old issue is hopefully no longer relevant.
