### ISSUE TITLE
Box2D imports fine, nothing else does

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#30]
_From [Anonymouse2048](https://code.google.com/u/108928530025329761891/) on April 01, 2010 12:37:46_

I tried to run every one of the examples from the testbed (after compiling 
pybox2d myself), and none of them worked because Box2D had no child 
objects.

For  example, test_Car.py:
Traceback (most recent call last):
  File "test_Car.py", line 22, in \<module>
    from test_main import *
  File "/home/linus/pybox2d-read-only/testbed/test_main.py", line 31, in 
\<module>
    exec("from &#37;s_main import *" &#37; fwSettings.backend)
  File "<string>", line 1, in \<module>
  File "/home/linus/pybox2d-read-only/testbed/pygame_main.py", line 57, in 
\<module>
    class fwDestructionListener(box2d.b2DestructionListener):
AttributeError: 'module' object has no attribute 'b2DestructionListener'

Here's why:

\>>> import Box2D
\>>> dir(Box2D)
['__builtins__', '__doc__', '__file__', '__loader__', '__name__', 
'__package__', '__path__', '__version__', '__version_info__']

I'm using the latest SVN version (currently 258) on ubuntu 9.10 (Karmic).

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=30_

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on November 04, 2010 18:30:44_

My guess would be that you ran the examples from the main directory. There were some issues with that.

For the upcoming version, the library files are placed in a different directory and so this should not be an issue any longer.

**Status:** WontFix

**Comment by kne** [comment]
_From [Anonymouse2048](https://code.google.com/u/108928530025329761891/) on November 05, 2010 15:00:21_

Um... No offence, but I mentioned how firstly, the error was found in one of the examples, and secondly that importing Box2D in the python shell gave me an empty module called Box2D.

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on November 05, 2010 15:04:21_

Yes, but you did not specify your current directory when running the python interpreter or the examples. 

Perhaps your issue is different than the one at the bottom of the wiki: https://code.google.com/p/pybox2d/wiki/BuildingfromSource I would need more information about your setup to determine whether or not it's an actual issue.

**Comment by kne** [comment]
_From [stodge](https://code.google.com/u/100796815837735259397/) on May 06, 2011 16:53:24_

I'm getting the same problem. What do you mean by: 

"For the upcoming version, the library files are placed in a different directory and so this should not be an issue any longer."

I did python setup.py install so I assumed the test bed apps would work.

**Comment by kne** [comment]
_From [stodge](https://code.google.com/u/100796815837735259397/) on May 06, 2011 16:59:12_

Never mind; this was using the download file. The latest trunk works. Thanks

**Comment by kne** [comment]
_From [Anonymouse2048](https://code.google.com/u/108928530025329761891/) on May 07, 2011 10:28:28_

Oh, I need to try the SVN version then... Sorry, I didn't see that you'd updated the issue, sirkne - I was running the python interpreter from my home directory.
