### ISSUE TITLE
segmentation fault in test_CollisionProcessing.py (from testbed)

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#31]
_From [claudiu725](https://code.google.com/u/107746382919527881317/) on May 01, 2010 13:17:15_

What steps will reproduce the problem? 1. Start test_CollisionProcessing.py (obviously)
2. press space (so a small circle will be spawned)
3. collide the big circle with the newly spawned one (so the small circle
would get destroyed)
4. press space a second time, and you get a segmentation fault

I used the testbed that came out with pybox2d ver. 2.0.2b1

It doesn't seem like an important bug, but i feel it should be taken care of.

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=31_

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on November 04, 2010 18:29:10_

Thanks for the report (and sorry for the late reply).

Seg faults are always important, but I think 2.0.2b1 has reached the end of its life cycle.

**Status:** WontFix

**Comment by kne** [comment]
_From [c0ffeeartc](https://code.google.com/u/104949198184898325357/) on August 10, 2013 04:33:52_

Same happens with pybox2d ver. 2.3b0 and python 2.7.5, Windows 8 64bit
Steps are the same and error says:
"Fatal Python error: (pygame parachute) Segmentation Fault"

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on August 10, 2013 12:29:26_

Reproduced. Backtrace is as follows:

Core was generated by `python test_CollisionProcessing.py'.
Program terminated with signal 6, Aborted.
\#0  0xb7759424 in __kernel_vsyscall ()
(gdb) bt
\#0  0xb7759424 in __kernel_vsyscall ()
\#1  0xb757bb1f in raise () from /lib/i386-linux-gnu/libc.so.6
\#2  0xb757f0b3 in abort () from /lib/i386-linux-gnu/libc.so.6
\#3  0x08096dc4 in Py_FatalError ()
\#4  0xb7752629 in ?? () from /usr/lib/python2.7/dist-packages/pygame/base.so
\#5  \<signal handler called>
\#6  0xb70d8c24 in b2ContactManager::Collide (this=this@entry=0x99de440) at Box2D/Dynamics/b2ContactManager.cpp:296
\#7  0xb70d60b7 in b2World::Step (this=this@entry=0x99c5268, dt=dt@entry=0.0166666675, velocityIterations=velocityIterations@entry=8, positionIterations=3) at Box2D/Dynamics/b2World.cpp:930
\#8  0xb70c46ce in _wrap_b2World_Step (args=0xb74675cc, kwargs=0x0) at Box2D/Box2D_wrap.cpp:14641
\#9  0x080bb299 in PyEval_EvalFrameEx ()
\#10 0x080b71c0 in PyEval_EvalFrameEx ()
\#11 0x080b71c0 in PyEval_EvalFrameEx ()
\#12 0x080b71c0 in PyEval_EvalFrameEx ()
\#13 0x080b71c0 in PyEval_EvalFrameEx ()
\#14 0x080b71c0 in PyEval_EvalFrameEx ()
\#15 0x080b71c0 in PyEval_EvalFrameEx ()
\#16 0x0811f939 in PyEval_EvalCodeEx ()
\#17 0x081836c7 in PyEval_EvalCode ()
\#18 0x08183b7d in ?? ()
\#19 0x080a6032 in PyRun_FileExFlags ()
\#20 0x080a65f8 in PyRun_SimpleFileExFlags ()
\#21 0x080a74af in Py_Main ()
\#22 0x080a7581 in main ()
(gdb) 

Not sure of cause as of yet...

**Status:** Accepted  
  **Labels:** -Priority-Medium Priority-High
