### ISSUE TITLE
accessing fixture.aABB raises an exception

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#34]
_From [mikkelin](https://code.google.com/u/108285140958627539736/) on October 17, 2010 08:44:11_

What steps will reproduce the problem? 1. fixture.aABB 2. 3. What is the expected output? What do you see instead? >>> fixture.aABB
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/Library/Python/2.6/site-packages/Box2D-2.1b0-py2.6-macosx-10.6-universal.egg/Box2D/Box2D.py", line 3227, in __GetAABB
    return _Box2D.b2Fixture___GetAABB(self, *args, **kwargs)
TypeError: Required argument 'childIndex' (pos 2) not found What version of the product are you using? On what operating system? branches/box2d_2.1, revision 275 Please provide any additional information below. C++ signature:

const b2AABB& b2Fixture::GetAABB(int32 childIndex) const

So, this C++ member function needs to be wrapped as a Python method, not a property.

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=34_

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on October 21, 2010 14:47:03_

Oops! aABB was a typo for the name, even.

Great -- keep them coming. :)

Should be fixed in r276 .

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on November 04, 2010 18:27:44_

**Status:** Fixed
