### ISSUE TITLE
Problem with pyBox2d and Python 2.7.2

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#45]
_From [pgrandeau](https://code.google.com/u/107936628890764972978/) on March 20, 2012 03:37:30_

I installed pyBox2D on Windows7 and Python 2.7.2 and when I run demos.py (in testbed) I get the error :

Traceback (most recent call last):
  File "C:\Users\...\testbed\demos.py", line 29, in \<module>
    from test_main import fwDebugDraw
  File "C:\Users\...\testbed\test_main.py", line 32, in \<module>
    exec("from &#37;s_main import *" &#37; fwSettings.backend)
  File "<string>", line 1, in \<module>
  File "C:\Users\Pascal\Desktop\pyBox2d\testbed\pygame_main.py", line 78, in \<module>
    class fwBoundaryListener(box2d.b2BoundaryListener):
AttributeError: 'module' object has no attribute 'b2BoundaryListener'

I do not know what this mean.
How can I use pyBox2D and testbed with my configuration ?
Thank you.

Pascal Grandeau

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=45_

**Comment by kne** [comment]
_From [djflyte](https://code.google.com/u/106538382479081335049/) on January 05, 2014 05:42:09_

As far as I can tell, b2BoundaryListener doesn't exist in the latest version of pybox2d. I guess we'll have to use an old version of pybox2d with the testbed.

**Comment by kne** [comment]
_From [djflyte](https://code.google.com/u/106538382479081335049/) on January 05, 2014 07:28:55_

Actually, it turns out the link to the testbed on the home page is for the old version, but there's an 'examples' directory in the zip file for the latest version (here, as of writing https://code.google.com/p/pybox2d/downloads/detail?name=Box2D-2.3b0.zip ) which I've just tested as working :)

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on January 05, 2014 08:32:00_

I don't know how I missed this issue -- but yes, the updated testbed is included with the source distribution as you've found. Sorry for it being such a tangled mess.

And yes, the boundary listener does not exist in the latest Box2D (and as such, pybox2d).  The world no longer has an explicit size limitation.
