### ISSUE TITLE
**kwargs does not have iteritems() in python3.3.3

### ISSUE THREAD

**Issue by kne** [pybox2d/pybox2d#53]
_From [charlie.burrows](https://code.google.com/u/104908006973867683469/) on January 19, 2014 11:46:08_

What steps will reproduce the problem? $ python examples/hello.py 
Traceback (most recent call last):
  File "examples/hello.py", line 14, in \<module>
    world=b2World() # default gravity is (0,-10) and doSleep is True
  File "/usr/lib/python3.3/site-packages/Box2D-2.3b0-py3.3-linux-x86_64.egg/Box2D/Box2D.py", line 4625, in __init__
    for key, value in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems' What is the expected output? What do you see instead? I expect to be able to create any of the box2d objects. Using python2.7 it works as expected. What version of pybox2d are you using? On what operating system? 32-bit or 64-bit? Archlinux x86_64 Please provide any additional information below. This idiom is used all over the place:
def test(**kwargs):
    for key, value in kwargs.iteritems():
        print(key)
test()

In python3 this results in:
AttributeError: 'dict' object has no attribute 'iteritems'

but in python2.7 there's no problem.

_Original issue: http://code.google.com/p/pybox2d/issues/detail?id=53_

**Comment by kne** [comment]
_From [charlie.burrows](https://code.google.com/u/104908006973867683469/) on January 19, 2014 09:55:22_

I suspect this is the fix but I don't know swig and can't get it working so I can't test it.

Index: Box2D/Box2D_kwargs.i

===================================================================
--- Box2D/Box2D_kwargs.i        ( revision 376 )
+++ Box2D/Box2D_kwargs.i        (working copy)
@@ -20,7 +20,7 @@
 
 %pythoncode %{
     def _init_kwargs(self, **kwargs):
-        for key, value in kwargs.iteritems():
+        for key, value in kwargs.items():
             try:
                 setattr(self, key, value)
             except:

**Comment by kne** [comment]
_From [sirkne](https://code.google.com/u/112841506218621786238/) on May 17, 2014 11:59:31_

Thanks for the report. I'll switch over to using items() exclusively from now on. Should be fixed in rev 377

**Status:** Fixed
