### ISSUE TITLE
_Box2D.so: undefined symbol:

### ISSUE THREAD

**Issue by amolchanov86** [pybox2d/pybox2d#87]
When I am trying to run openai gym on Ubuntu 16.04 I have an error:
Traceback (most recent call last):
  File "./run_pg.py", line 22, in <module>
    env_src = make(args.env)
  File "/opt/anaconda2/lib/python2.7/site-packages/gym/envs/registration.py", line 140, in make
    return registry.make(id)
  File "/opt/anaconda2/lib/python2.7/site-packages/gym/envs/registration.py", line 105, in make
    return spec.make()
  File "/opt/anaconda2/lib/python2.7/site-packages/gym/envs/registration.py", line 69, in make
    cls = load(self._entry_point)
  File "/opt/anaconda2/lib/python2.7/site-packages/gym/envs/registration.py", line 18, in load
    result = entry_point.load(False)
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/anaconda2/lib/python2.7/site-packages/gym/envs/box2d/__init__.py", line 1, in <module>
    from gym.envs.box2d.lunar_lander import LunarLander
  File "/opt/anaconda2/lib/python2.7/site-packages/gym/envs/box2d/lunar_lander.py", line 4, in <module>
    import Box2D
  File "/opt/anaconda2/lib/python2.7/site-packages/Box2D/__init__.py", line 20, in <module>
    from .Box2D import *
  File "/opt/anaconda2/lib/python2.7/site-packages/Box2D/Box2D.py", line 32, in <module>
    _Box2D = swig_import_helper()
  File "/opt/anaconda2/lib/python2.7/site-packages/Box2D/Box2D.py", line 28, in swig_import_helper
    _mod = imp.load_module('_Box2D', fp, pathname, description)
ImportError: /opt/anaconda2/lib/python2.7/site-packages/Box2D/_Box2D.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm

What could be the problem ?

**Comment by garibarba** [comment]
I'm having exactly this same error. Did you manage to solve it?

I'm using python3.5 from anaconda, also on ubuntu 16.04.

`ImportError: /home/user/.local/anaconda3/lib/python3.5/site-packages/Box2D/_Box2D.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm`

**Comment by garibarba** [comment]
This fixed it for me:
http://stackoverflow.com/questions/40710687/persistent-issues-with-installation-of-openai-gym

**Comment by Faur** [comment]
Solution by WonH did it for me

**Comment by kne** [comment]
New builds that solve this issue will be available on the conda-forge channel with conda.

To install, use: `conda install -c conda-forge pybox2d`
