### ISSUE TITLE
Remove / replace deprecated use of _swigconstant

### ISSUE THREAD

**Issue by martin-langhoff** [pybox2d/pybox2d#88]
Swig removed `_swigconstant` in their fix to https://github.com/swig/swig/issues/563 , this leads to errors in PyBox2d like:

```
pilasengine
Traceback (most recent call last):
  File "/usr/bin/pilasengine", line 6, in <module>
    import pilasengine
  File "/usr/lib/python2.7/site-packages/pilasengine/__init__.py", line 23, in <module>
    import escenas
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/__init__.py", line 12, in <module>
    from pilasengine.escenas.normal import Normal
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/normal.py", line 7, in <module>
    from pilasengine.escenas.escena import Escena
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/escena.py", line 14, in <module>
    from pilasengine.fisica import Fisica
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/__init__.py", line 9, in <module>
    from pilasengine.fisica.contact_listener import ObjetosContactListener
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/contact_listener.py", line 9, in <module>
    import Box2D as box2d
  File "/usr/lib64/python2.7/site-packages/Box2D/__init__.py", line 19, in <module>
    from .Box2D import *
  File "/usr/lib64/python2.7/site-packages/Box2D/Box2D.py", line 435, in <module>
    _Box2D.RAND_LIMIT_swigconstant(_Box2D)
```

this affects downstreams:

* https://github.com/openai/gym/issues/100
* https://github.com/hugoruscitti/pilas/issues/294

I am not familiar enough w PyBox2d nor Swig to propose a good fix :-/

**Comment by Mistobaan** [comment]
came here from the openai/gym

**Comment by kne** [comment]
The pre-built `Box2D.py` will be removed from the repository shortly.
To avoid building on your own, please use conda-forge pybox2d:

`conda install -c conda-forge pybox2d`
